version: '3.5'
services:
  global-nginx-proxy:
    image: jwilder/nginx-proxy
    restart: ${RESTART:-unless-stopped}
    ports:
      - "${HTTP_IP:-127.0.0.1}:${HTTP_PORT:-80}:80"
      - "${HTTPS_IP:-127.0.0.1}:${HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./global-nginx-proxy/additional_nginx.conf:/etc/nginx/conf.d/additional_nginx.conf
      - ./.docker/global-nginx-proxy/certs:/etc/nginx/certs:ro
      - ./.docker/global-nginx-proxy/dhparam:/etc/nginx/dhparam

  global-db:
    image: mariadb:10.4
    restart: ${RESTART:-unless-stopped}
    ports:
      - "${DB_IP:-127.0.0.1}:${DB_PORT:-3306}:3306"
    volumes:
      - ./.docker/global-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=16MB --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  global-mail:
    image: mailhog/mailhog
    restart: ${RESTART:-unless-stopped}
    ports:
      - "${SMTP_PORT:-1025}:1025"
    environment:
      - VIRTUAL_HOST=${MAIL_VIRTUAL_HOST:-~^mail\.(localhost|vm\d+\.example\.org)$$}
      - VIRTUAL_PORT=8025

  global-portainer:
    image: portainer/portainer-ce
    restart: ${RESTART:-unless-stopped}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/global-portainer:/data
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST:-~^portainer\.(localhost|vm\d+\.example\.org)$$}
      - VIRTUAL_PORT=9000

networks:
  default:
    external:
      name: global
