services:
  web:
    image: webdevops/php-apache:8.3
    restart: always
    volumes:
      - ./.docker/roundmail:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - APPLICATION_UID=${APPLICATION_UID:-501}
      - APPLICATION_GID=${APPLICATION_GID:-80}
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail_www.rule=(Host(`mail.org`) || Host(`www.mail.org`) || Host(`mail.mail.org`) || Host(`pop.mail.org`) || Host(`imap.mail.org`) || Host(`smtp.mail.org`))
      - traefik.http.routers.mail_www.middlewares=mail_redirect,redirect-www@file

      # TLS
      - traefik.http.routers.mail_www.entrypoints=websecure
      - traefik.http.routers.mail_www.tls=true
      - traefik.http.routers.mail_www.tls.certresolver=letsEncrypt

      # Middelware: Redirect alternative domain to main domain
      - "traefik.http.middlewares.mail_redirect.redirectregex.regex=^(https?)://(mail|pop|imap|smtp)\\.mail\\.org/(.*)"
      - "traefik.http.middlewares.mail_redirect.redirectregex.replacement=https://mail.org"
      - "traefik.http.middlewares.mail_redirect.redirectregex.permanent=true"
    working_dir: /app

  roundcube:
    build: ./build-roundcubemail
    #image: roundcube/roundcubemail:latest
    #container_name: roundcube
    restart: always
    volumes:
      - ./.docker/roundmail:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=global-db
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=password

      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.mail.org
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://smtp.mail.org
      - ROUNDCUBEMAIL_SMTP_PORT=465
      # Internal: https://github.com/roundcube/roundcubemail/tree/master/plugins
      # External see Dockerfile: https://plugins.roundcube.net/
      - ROUNDCUBEMAIL_PLUGINS=archive,carddav,managesieve,markasjunk,newmail_notifier,zipdownload

  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    restart: always
    hostname: mail
    domainname: mail.org
    #container_name: mail
    ports:
      # receiving email from other mailservers
      - "0.0.0.0:25:25"
      # StartTLS: POP3, IMAP, SMTP
      - "0.0.0.0:110:110"
      - "0.0.0.0:143:143"
      - "0.0.0.0:587:587"
      # SSL: POP3, IMAP, SMTP
      - "0.0.0.0:995:995"
      - "0.0.0.0:993:993"
      - "0.0.0.0:465:465"
       # Manage Sieve port
      - "0.0.0.0:4190:4190"

      - "127.0.0.1:11334:11334" # Rspamd web interface
    volumes:
      - ./.docker/mail/config:/tmp/docker-mailserver
      - ./.docker/mail/data:/var/mail
      - ./.docker/mail/state:/var/mail-state
      - ./.docker/mail/logs:/var/log/mail
      - ./.docker/mail/cron:/tmp/cron
      - ./.docker/mail/cron/sa-learn:/etc/cron.d/sa-learn
      - /etc/localtime:/etc/localtime:ro
      - ../global/.docker/traefik/acme/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.org

      #- OVERRIDE_HOSTNAME=mail.org
      - ENABLE_POP3=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ONE_DIR=1
      # Debug: Enable debug on startup
      #- DMS_DEBUG=1

      # Message size 100 MB
      - POSTFIX_MESSAGE_SIZE_LIMIT=104857600

      - ENABLE_POSTGREY=1
      # greylist for N seconds
      - POSTGREY_DELAY=300
      # delete entries older than N days since the last time that they have been seen
      - POSTGREY_MAX_AGE=35
      # response when a mail is greylisted
      - POSTGREY_TEXT=Delayed by postgrey
      # whitelist host after N successful deliveries (N=0 to disable whitelisting)
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5

      # Rspamd
      - ENABLE_RSPAMD=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0

      #- ENABLE_SPAMASSASSIN=1
      - "SA_SPAM_SUBJECT=[SPAM] "
      # add spam info headers if at, or above that level
      - SA_TAG=0.5
      # add 'spam detected' (SA_SPAM_SUBJECT) headers at that level
      - SA_TAG2=3.5
      # triggers spam evasive actions
      - SA_KILL=6.0

      # Debug: Ignore the failure of this test - Allow other tests to complete
      #- POSTSCREEN_ACTION=ignore
      # Mail spoofing denied - Send mails only from existing mail or alias
      - SPOOF_PROTECTION=1
      # Enables Managesieve on port 4190
      - ENABLE_MANAGESIEVE=1
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  autodiscover:
    image: monogramm/autodiscover-email-settings:latest
    environment:
      #- VIRTUAL_PORT=8000
      - COMPANY_NAME=Mail
      - SUPPORT_URL=https://autodiscover.mail.org
      - DOMAIN=mail.org
      - IMAP_HOST=mail.mail.org
      - IMAP_PORT=993
      - IMAP_SOCKET=SSL
      - POP_HOST=mail.mail.org
      - POP_PORT=993
      - POP_SOCKET=SSL
      - SMTP_HOST=mail.mail.org
      - SMTP_PORT=465
      - SMTP_SOCKET=SSL
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail_autoconfig.rule=(Host(`autoconfig.mail.org`) || Host(`autodiscover.mail.org`) || Host(`autoconfig.example.org`) || Host(`autodiscover.example.org`))

      # TLS
      - traefik.http.routers.mail_autoconfig.entrypoints=websecure
      - traefik.http.routers.mail_autoconfig.tls=true
      - traefik.http.routers.mail_autoconfig.tls.certresolver=letsEncrypt

networks:
  default:
    external: true
    name: global
